export default {
  body: document.body,
  title: document.querySelector('h1'),
  description: document.querySelector('.lead'),
  form: document.querySelector('form'),
  input: document.querySelector('#url-input'),
  submitButton: document.querySelector('button[type="submit"]'),
  example: document.querySelector('#example'),
  feedBack: document.querySelector('.feedback'),
  posts: document.querySelector('.posts'),
  feeds: document.querySelector('.feeds'),
  modalWindow: document.querySelector('.modal'),
  modal: document.querySelector('.modal-content'),
  modalTitle: document.querySelector('.modal-title'),
  modalBody: document.querySelector('.modal-body'),
  modalLink: document.querySelector('a'),
  modalClose: modal.querySelectorAll('button'),
};
